### ISSUE TITLE
Error building binding `LLVM ERROR: invalid vector instr` and `warning: cannot represent a NaN literal`

### ISSUE THREAD

**Issue by marcj** [Zubnix/skia-wasm-port#3]
Hi,

I get following error when trying to build this repository using `./build_bindings.sh`. `build_skia_wasm_bitcode.sh` runs fine.

I use emscripten v1.38.6 on macOS 10.12.4. Any idea what this can be?

```
marc@osx ~/bude/skia-wasm-port (master*) $ ./build_bindings.sh
Compiling bindings to bitcode
Generating final wasm
emcc: warning: cannot represent a NaN literal '0x7f8fea068040' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   store float 0x7FFFFFFFE0000000, float* %6, align 4, !tbaa !3 in _ZN6SkRect16setBoundsNoCheckEPK7SkPointi()
emcc: warning: cannot represent a NaN literal '0x7f8fea068040' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   store float 0x7FFFFFFFE0000000, float* %7, align 4, !tbaa !8 in _ZN6SkRect16setBoundsNoCheckEPK7SkPointi()
emcc: warning: cannot represent a NaN literal '0x7f8fea068040' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   store float 0x7FFFFFFFE0000000, float* %8, align 4, !tbaa !9 in _ZN6SkRect16setBoundsNoCheckEPK7SkPointi()
emcc: warning: cannot represent a NaN literal '0x7f8fea068040' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   store float 0x7FFFFFFFE0000000, float* %9, align 4, !tbaa !10 in _ZN6SkRect16setBoundsNoCheckEPK7SkPointi()
LLVM ERROR: invalid vector instr
Traceback (most recent call last):
  File "/Users/marc/bude/pestoGui/libs/emsdk/emscripten/1.38.6/emcc", line 11, in <module>
    python_selector.run(__file__)
  File "/Users/marc/bude/pestoGui/libs/emsdk/emscripten/1.38.6/tools/python_selector.py", line 38, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/Users/marc/bude/pestoGui/libs/emsdk/emscripten/1.38.6/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/Users/marc/bude/pestoGui/libs/emsdk/emscripten/1.38.6/emcc.py", line 1673, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/Users/marc/bude/pestoGui/libs/emsdk/emscripten/1.38.6/tools/shared.py", line 2042, in emscripten
    emscripten._main(cmdline)
  File "/Users/marc/bude/pestoGui/libs/emsdk/emscripten/1.38.6/emscripten.py", line 2383, in _main
    temp_files.run_and_clean(lambda: main(
  File "/Users/marc/bude/pestoGui/libs/emsdk/emscripten/1.38.6/tools/tempfiles.py", line 93, in run_and_clean
    return func()
  File "/Users/marc/bude/pestoGui/libs/emsdk/emscripten/1.38.6/emscripten.py", line 2388, in <lambda>
    DEBUG=DEBUG,
  File "/Users/marc/bude/pestoGui/libs/emsdk/emscripten/1.38.6/emscripten.py", line 2296, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/Users/marc/bude/pestoGui/libs/emsdk/emscripten/1.38.6/emscripten.py", line 84, in emscript
    backend_output = compile_js(infile, settings, temp_files, DEBUG)
  File "/Users/marc/bude/pestoGui/libs/emsdk/emscripten/1.38.6/emscripten.py", line 113, in compile_js
    shared.jsrun.timeout_run(subprocess.Popen(backend_args, stdout=subprocess.PIPE, universal_newlines=True), note_args=backend_args)
  File "/Users/marc/bude/pestoGui/libs/emsdk/emscripten/1.38.6/tools/jsrun.py", line 20, in timeout_run
    raise Exception('Subprocess "' + ' '.join(note_args) + '" failed with exit code ' + str(proc.returncode) + '!')
Exception: Subprocess "/Users/marc/bude/pestoGui/libs/emsdk/clang/e1.38.6_64bit/llc /tmp/tmpNWiD9u/skia.bc -march=js -filetype=asm -o /tmp/tmpCLYNSK.4.js -emscripten-stack-size=5242880 -O3 -emscripten-precise-f32 -emscripten-global-base=1024 -emscripten-no-exit-runtime -emscripten-wasm -emscripten-only-wasm" failed with exit code 1!
```

My libskia.a got built using skia from commit https://github.com/google/skia/commit/c9a424731a891fc837ed99371a10442584c2e01d

```
-rw-r--r--   1 marc  staff    25M Jun 25 21:08 libskia.a
```

**Comment by Zubnix** [comment]
It's probably this bug:
https://bugs.chromium.org/p/skia/issues/detail?id=8045#c1

So using a more recent Skia version should fix it?

**Comment by marcj** [comment]
Just as a side note, just tried newest https://github.com/kripken/emscripten/commit/70085740dceff2066a643ad54c2eae1931c5748e, which didn't work either. Trying now newest skia version.

**Comment by Zubnix** [comment]
Alternatively you can use: https://github.com/Zubnix/skia-wasm-port/blob/master/libskia.a
That version also has webgl enabled fixes which you don't get if you build Skia from upstream source.

If you really want to build skia bitcode from source, you could also try a commit from shortly after the mentioned bug report got closed, as that is also the version that was used to build the libskia.a included in this repo.

**Comment by marcj** [comment]
I see, thanks! I got it building now using https://github.com/google/skia/commit/d4b2adeaa929edd1664754ac6621ec524992ef03 after clearing the emcc cache. The examples *.js work fine now, thanks for the support. :) Will now try to get it running in Browsers using WebGL.

> That version also has webgl enabled fixes which you don't get if you build Skia from upstream source.

Mh, I see. So this means those fixes are not open-sourced?

**Comment by Zubnix** [comment]
> Mh, I see. So this means those fixes are not open-sourced?

They're hacks, that's why it's not in upstream Skia. More info here: https://bugs.chromium.org/p/skia/issues/detail?id=8041#c12

Future Skia will have proper WebGL

**Comment by marcj** [comment]
Ah ok, thanks for the details! Makes sense to not include them in Skia yet. I rather thought about a patch file maybe, you used to get it running. :)

Btw, did you get it running with WebGL 1 or 2?

**Comment by Zubnix** [comment]
The changes I did are in comment 12 of  the ticket. I'll see if I can add a patch file to the repo.

I believe I used WebGL 1. WebGL 2 didn't work for some unknown reason.

**Comment by marcj** [comment]
Ok, cool, thanks!
